// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyAtHomes_WebApi.Context;

namespace PartyAtHomes_WebApi.Migrations
{
    [DbContext(typeof(PartyAtHomesContext))]
    partial class PartyAtHomesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PartyAtHomes_Lib.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LocationLat")
                        .HasColumnType("float");

                    b.Property<double>("LocationLng")
                        .HasColumnType("float");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AdressCity = "Tielt",
                            AdressCountry = "Belgium",
                            AdressNumber = "3",
                            AdressStreet = "Sint Janstraat",
                            CreatorId = new Guid("d9aa745e-a3c0-4fe6-95a6-40e80af5b1d5"),
                            DescriptionEvent = "test event tielt",
                            EndDateTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Test1",
                            LocationLat = 0.0,
                            LocationLng = 0.0,
                            MainImage = "paris.jpg",
                            StartDateTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            AdressCity = "Brugge",
                            AdressCountry = "Belgium",
                            AdressNumber = "3",
                            AdressStreet = "Rijselstraat",
                            CreatorId = new Guid("d9aa745e-a3c0-4fe6-95a6-40e80af5b1d5"),
                            DescriptionEvent = "Test Event Brugge",
                            EndDateTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Test2",
                            LocationLat = 0.0,
                            LocationLng = 0.0,
                            MainImage = "paris.jpg",
                            StartDateTime = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PartyAtHomes_Lib.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9aa745e-a3c0-4fe6-95a6-40e80af5b1d5"),
                            FirstName = "chakalaka",
                            LastName = "Boom Boom",
                            Password = "123AZERTY",
                            UserName = "ChakBoom"
                        });
                });

            modelBuilder.Entity("PartyAtHomes_Lib.Event", b =>
                {
                    b.HasOne("PartyAtHomes_Lib.User", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
